Armadio/urls.py
from django.urls import path

from Armadio import views

app_name = 'Armadio'

urlpatterns = [
    path('', views.home, name='home'),
    path('sitemap.xml/',views.sitemap, name='sitemap'),
    path('robots.txt/', views.robots, name='robots')
]

blog/urls.py
from django.urls import path
from blog import views
from blog.views import PostList, PostDetail, PostByCategory

app_name = 'blog'

urlpatterns = [
  path("post_list/", PostList.as_view(), name="post_list"),
  path("<slug:slug>/", PostDetail.as_view(), name="post_detail"),

  path("category/<str:slug>/", PostByCategory.as_view(), name="post_by_category"),

]

project/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('Armadio.urls', namespace='home')),
    path('summernote/', include('django_summernote.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    prefix_default_language=False,
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Armadio/models.py
from django.db import models

# Create your models here.

blog/models.py
import sys
from io import BytesIO

from PIL import Image
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)  # Call the real save() method

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.CharField(max_length=100)
    image_author = models.ImageField(upload_to='post/', blank=True, null=True)
    title = models.CharField(max_length=100)
    tags = models.ManyToManyField(Tag)
    post_views = models.PositiveIntegerField(default=0)
    image_home = models.ImageField(upload_to='post/', blank=True, null=True)
    image_list = models.ImageField(upload_to='post/', blank=True, null=True)
    image_detail_head = models.ImageField(upload_to='post/', blank=True, null=True)
    image_detail_body = models.ImageField(upload_to='post/', blank=True, null=True)
    created_at = models.DateField()
    description_one = models.TextField()
    description_two = models.TextField()
    description_three = models.TextField()
    description_blockquote = models.TextField()
    category = models.ManyToManyField(Category, related_name='post_category')
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)  # Call the real save() method

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['created_at']

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

Armadio/views.py
from django.shortcuts import render

# Create your views here.

from blog.models import Post


def home(request):
    posts = Post.objects.all()[:3]
    return render(request, 'home/index.html', {
        'posts': posts,
    })


def sitemap(request):
    return render(request, 'home/sitemap.xml')


def robots(request):
    return render(request, 'home/robots.txt')

blog/views.py
from django.db.models import Q, Count
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView

from blog.models import Post, Category, Tag


class PostList(ListView):
    model = Post
    paginate_by = 10 # pagination
    template_name = 'blog/post_list.html'
    queryset = Post.objects.order_by('created_at')

    def get_queryset(self):
        name = self.request.GET.get('q', '')
        object_list = Post.objects.filter(
            Q(title__icontains=name) |
            Q(description_one__icontains=name) |
            Q(description_two__icontains=name)
        )
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all().annotate(post_count=Count('post_category'))
        context["tags"] = Tag.objects.all()
        return context


class PostDetail(DetailView):
    model = Post

    def get_object(self):
        post = super().get_object()
        post.post_views += 1
        post.save()
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        return context


class PostByCategory(ListView):
    model = Post

    def get_queryset(self):
        slug = self.kwargs['slug']
        object_list = Post.objects.filter(
            Q(category__name__icontains=slug)
        )
        return object_list

templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block body %}

    <!--Page Title-->

    <section class="page-title">
        <div class="auto-container">
            <div class="inner-container clearfix">

            </div>
        </div>
    </section>

    <!--End Page Title-->

    <!-- Blog Detail -->
    <div class="blog-detail style-two">
        <div class="inner-container">
            <!-- News Block -->
            <div class="news-block-two">
                <div class="inner-box">
                     <div class="image-box">
                        <figure class="image"><img src="{{post.image_detail_head.url}}" alt=""></figure>
                    </div>

                    <div class="caption-box">
                        <div class="inner">
                            <h3>{{post.title}}</h3>
                            <ul class="info">
                                <li>{{post.created_at|date:"F j, Y"}}</li>
                                <li><a href="#">{{post.author}}</a></li>
                            </ul>
                            <p>{{post.description_one|safe}}</p>
                            <blockquote>
                                <i class="fa fa-quote-left"></i> {{post.description_blockquote|safe}}
                            </blockquote>
                            <div class="tow-column row">
                                <div class="image-column col-lg-6 col-md-12 col-sm-12">
                                    <figure class="image"><img src="{{post.image_detail_body.url}}" alt=""></figure>
                                </div>
                                <div class="text-column col-lg-6 col-md-12 col-sm-12">
                                    <p>{{post.description_two|safe}}</p>
                                </div>
                            </div>
                            <p>{{post.description_three|safe}}</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Tags -->
            <div class="tags clearfix">
                <span class="title">{% trans "Tags:" %}</span>
                {% for tag in tags %}
                <ul>
                    <li><a >{{tag.name}}</a></li>
                </ul>
                {% endfor %}
            </div>

        
           
        </div>
    </div>
    <!-- End Blog Detail -->


{% endblock body %}




templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block body %}
    <!--Page Title-->
    <section class="page-title">
        <div class="auto-container">
            <div class="inner-container clearfix">

            </div>
        </div>
    </section>
    <!--End Page Title-->

    <!-- Sidebar Page Container -->
    <div class="sidebar-page-container">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Content Side-->
                <div class="content-side col-lg-8 col-md-12 col-sm-12">
                    <div class="blog-classic">
                        <!-- News Block -->
                         {% for post in object_list %}
                        <div class="news-block-two wow fadeIn">
                            <div class="inner-box">
                                <div class="image-box">
                                    <figure class="image"><a href="#"><img src="{{post.image_list.url}}" alt=""></a></figure>
                                </div>
                                <div class="caption-box">
                                    <div class="inner">
                                        <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
                                        <ul class="info">
                                            <li><a href="{{post.get_absolute_url}}">{{post.created_at|date:"F j, Y"}}</a></li>
                                            <li>{{post.author}}</li>
                                        </ul>
                                        <div class="text">{{post.description|safe}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <!--Post Share Options-->
                     {% if is_paginated %}
                        <div class="styled-pagination">
                        <ul class="clearfix">
                            {% if page_obj.has_previous %}
                            <li class="prev-post"><a href="?page={{ page_obj.previous_page_number }}">
                                <span class="fas fa-long-arrow-alt-left"></span> {% trans "Prev" %}</a>
                            </li>
                            {% else %}
                            <li class="prev-post disabled"><a href="#">
                                <span class="fas fa-long-arrow-alt-left"></span> {% trans "Prev" %}</a>
                            </li>

                            {% endif %}

                            {% for i in paginator.page_range %}
                                {% if page_obj.number == i %}
                                <li class=""><a href="?page={{ i }}">{{ i }}</a></li>
                                {% else %}
                                <li class=""><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
				            {% endfor %}


                            {% if page_obj.has_next %}
                            <li class="next-post"><a href="?page={{ page_obj.next_page_number }}">
                                <span class="fas fa-long-arrow-alt-right"></span> {% trans "Next" %}</a>
                            </li>
                            {% else %}
                            <li class="next-post disabled"><a href="#">
                                <span class="fas fa-long-arrow-alt-right"></span> {% trans "Next" %}</a>
                            </li>

                            {% endif %}
                        </ul>
                    </div>
                     {% endif %}

                </div>

                <!--Sidebar Side-->
                <div class="sidebar-side col-lg-4 col-md-12 col-sm-12">
                    <aside class="sidebar default-sidebar">

                        <!--search box-->
                        <div class="sidebar-widget search-box">
                            <form action="{% url 'blog:post_list' %}" method="GET">
                                <div class="form-group">
                                    <input type="search" name="q" value="" placeholder="{% trans 'Search.....' %}" required="">
                                    <button type="submit"><span class="icon fa fa-search"></span></button>
                                </div>
                            </form>
                        </div>

                        <!-- Categories -->
                        <div class="sidebar-widget categories">
                            <div class="sidebar-title"><h3>{% trans "Catagories" %}</h3></div>

                            <ul class="cat-list">
                            {% for category in categories %}
                                <li><a href="{% url 'blog:post_by_category' category.slug %}">{{category.name}} <span>({{category.post_count}})</span></a></li>
                            {% endfor %}
                            </ul>

                        </div>

                         <!-- Latest News -->
                        <div class="sidebar-widget latest-news">
                            <div class="sidebar-title"><h3>{% trans "Recent Post" %}</h3></div>
                            <div class="widget-content">
                                {% for post in recent_posts %}
                                <article class="post">
                                    <div class="post-thumb"><a href="{{post.get_absolute_url}}"><img src="{{post.image.url}}" alt=""></a></div>
                                    <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
                                    <div class="post-info">{{post.author}}</div>
                                </article>
                                {% endfor %}
                            </div>
                        </div>

                        <!-- Tags -->
                        <div class="sidebar-widget tags">
                            <div class="sidebar-title"><h3>{% trans "Keywords" %}</h3></div>
                             {% for tag in tags %}
                            <ul class="tag-list clearfix">
                                <li><a href="#">{{tag.name}}</a></li>
                            </ul>
                            {% endfor %}
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </div>
    <!-- End Sidebar Container -->

{% endblock body %}